_format_version: "3.0"
_transform: true

services:
  # Keycloakサービス
  - name: keycloak-service
    url: http://keycloak:8080
    routes:
      - name: keycloak-route
        paths:
          - /auth
        strip_path: false
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600
          preflight_continue: false

  # MidPointサービス
  - name: midpoint-service
    url: http://midpoint:8080
    routes:
      - name: midpoint-route
        paths:
          - /midpoint
        strip_path: false
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600
          preflight_continue: false

consumers:
  - username: api-consumer
    custom_id: api-consumer-id
    keyauth_credentials:
      - key: api-consumer-key

plugins:
  # グローバルレート制限
  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      policy: local

  # リクエストIDの追加
  - name: correlation-id
    config:
      header_name: Kong-Request-ID
      generator: uuid
      echo_downstream: true

  # ログ設定
  - name: file-log
    config:
      path: /usr/local/kong/logs/access.log
      reopen: true